### ISSUE TITLE
Prune Job Failed

### ISSUE THREAD

**Issue by vitaleg** [cyborgbackup/cyborgbackup#71]
Log:

Identity added: /tmp/cyborgbackup_181_mfs80m86/credential_cyborgbackup_ssh_key (cyborg@cyborg.local)
sh: 1: borg: not found

Borg is installed on both the client and the repository. All previous tasks have been completed successfully.

**Comment by GaetanF** [comment]
Hello,

Did you use the docker compose system or the debian binary install ?

Regards

**Comment by vitaleg** [comment]
Docker compose

**Comment by vitaleg** [comment]
Installing the Debian package has the same result. Prune job does not work.

**Comment by vitaleg** [comment]
I see what the problem is.
The cyborgbackup server must also have borg installed.

**Comment by morsedl** [comment]
As described in #54, installing `borgbackup` into the celery container (not celery_beat container) seems to fix this.

However, after doing so, and because we are using unencrypted backups, we no longer get the message reported here in the original post (OP):

```
Identity added: /tmp/cyborgbackup_31_9p6pd_pp/credential_cyborgbackup_ssh_key (cyborg@cyborg.loca
sh: 1: borg: not found
```

but rather:

```
Identity added: /tmp/cyborgbackup_34_lzgvbze3/credential_cyborgbackup_ssh_key (cyborg@cyborg.loca
Remote: Warning: Permanently added 'backup,10.0.2.6' (ECDSA) to the list of known hosts
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN
```

in the (output) console shown when viewing the prune job's details.

Any thoughts on how to address this?

I suspect this may require adding a general setting somewhere to pass parameters to native `borg` in order to be able to provide workarounds for unusual cases like ours.

We already have cron jobs set up on each client to accomplish the pruning with precisely the same pruning parameters we specify in Cyborg Backup (CB). But if we are doing the pruning outside of CB's awareness, then I strongly suspect our Catalog data as shown within CB will be incorrect, specifically, that it will continue to show archive (backup) runs in the Catalog that have been pruned.

So getting this fixed is likely important in order to have CB running correctly and in a sensibe fashion.
